app1/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'app1'
urlpatterns = [
    path("", views.index, name="Home"),
    path("car/<int:com_id>/", views.detail, name="detail"),
    path('about/', views.about , name="about"),
    path('contact/', views.contact, name="contact"),
    path(r'login/', views.login_request, name="login"),
    path(r'signup/', views.registration_request, name="signup"),
    path(r'logout/', views.logout_request, name="LogOut"),

    # path for contact us view

    # path for registration

    # path for login

    # path for logout

    # path(route='', view=views.get_dealerships, name='index'),

    # path for dealer reviews view

    # path for add a review view

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    # path('/', include('djangoapp.urls')),
    path('admin/', admin.site.urls),
    # path('', views.index),
    path(r"", include('app1.urls'), name="app1"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app1/models.py
from django.db import models
from django.utils.timezone import now

class cardealer(models.Model):
    name= models.CharField(max_length=100)
    # experience = models.IntegerField()
    detail = models.TextField()
    def __str__(self):
        return self.name


class carmake(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    color = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class carmodel(models.Model):
    name = models.CharField(max_length=100)
    year = models.DateField()
    cartype= models.CharField(max_length=200)
    dealer = models.ForeignKey(cardealer, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name

class carreview(models.Model):
    name = models.CharField(max_length=100)
    comment = models.TextField()
    com = models.ForeignKey(carmodel, on_delete = models.CASCADE)


# <HINT> Create a Car Model model `class CarModel(models.Model):`:
# - Many-To-One relationship to Car Make model (One Car Make has many Car Models, using ForeignKey field)
# - Name
# - Dealer id, used to refer a dealer created in cloudant database
# - Type (CharField with a choices argument to provide limited choices such as Sedan, SUV, WAGON, etc.)
# - Year (DateField)
# - Any other fields you would like to include in car model
# - __str__ method to print a car make object


# <HINT> Create a plain Python class `CarDealer` to hold dealer data


# <HINT> Create a plain Python class `DealerReview` to hold review data

app1/forms.py
from django.forms import ModelForm
from .models import carreview

class reviewform(ModelForm):
    class Meta:
        model = carreview
        fields = '__all__'

app1/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, redirect
# from .models import related models
# from .restapis import related methods
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from datetime import datetime
import logging
import json
from django.contrib.auth.forms import UserCreationForm,  AuthenticationForm
from django.contrib.auth import login, logout
# from django.contrib.auth.forms import

from .models import cardealer, carmodel
from .forms import reviewform


# Get an instance of a logger
logger = logging.getLogger(__name__)


# # # Create your views here.
# def index(request):
#     a = cardealer.objects.all()
#     context ={ 
#         'a':a
#     }
#     return render(request,"index2.html", context)


# Create an `about` view to render a static about page
def about(request):
    a = 0
    context= {
        "a":a
    }
    return render(request, 'about.html', context)


def contact(request):
    return render(request, 'contact.html')

def login_request(request):
    if request.user.is_authenticated:
        return redirect('/')
    else:
        form = AuthenticationForm()
        if request.method == 'POST':
            form = AuthenticationForm(request.POST)
            username = request.POST['username']
            password = request.POST['password1']
            user = authenticate(username= username, password= password)
            if user is not None:
                login(request,user)
                return redirect('/car')

    context={
        "form": form
    }
    return render(request, 'login.html', context)

def registration_request(request):
    if request.user.is_authenticated:
        return redirect('/')
    else:
        form = UserCreationForm()
        if request.method == 'POST':
            form = UserCreationForm(request.POST)
            if form.is_valid:
                form.save()
        return render(request, 'signup.html', {'form': form})

def logout_request(request):
    logout(request)
    return redirect('/')

# Create a `contact` view to return a static contact page
#def contact(request):

# Create a `login_request` view to handle sign in request
# def login_request(request):
# ...

# Create a `logout_request` view to handle sign out request
# def logout_request(request):
# ...

# Create a `registration_request` view to handle sign up request
# def registration_request(request):
# ...

# # Update the `get_dealerships` view to render the index page with a list of dealerships
def index(request):
    ca = cardealer.objects.all()
    pran = "pranav"
    context={
        'ca': ca,
        'pran':pran
    }
    return render(request, 'index.html', context)

def detail(request, com_id):
    a = cardealer.objects.get(id=com_id)
    b = a.carmodel_set.all()
    form = reviewform()
    if request.method == 'POST':
        form= reviewform(request.POST)
        if b.is_valid:
            form.save()
    context={
        'b':b,
        'form':form
    }
    return render(request, 'detail.html', context)

# Create a `get_dealer_details` view to render the reviews of a dealer
# def get_dealer_details(request, dealer_id):
# ...

# Create a `add_review` view to submit a review
# def add_review(request, dealer_id):
# ...

project1/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

templates/about.html
{% extends 'base.html' %}

{% block content %}

    <div class="jumbotron" style="height:400px; width:100%;">
        <div class="container">
            <h1 class="display-4">About Us </h1>
            <h5 class="display-1" style="font-size: 14px;">
                Welcome to Best Cars dealership, home to the best cars in North America. We sell domestic and imported cars at reasonable prices.
                <br>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero tempora a non quidem quasi recusandae quia quod, soluta, odio exercitationem similique rerum corrupti reprehenderit velit, totam aut? Eaque rem qui perspiciatis maiores et consequuntur quae perferendis magnam inventore tempora atque aperiam voluptates vero, delectus distinctio? Facilis, eos voluptate. Atque nisi illo minus in cupiditate.
            </h5>
        </div>
    </div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pranav Django Website</title>
    <style>
        .myhover{
            background:rgb(235, 233, 233);
            color:black;
        }
        .myhover:hover{
            background:white;
            color:black;
        }
    </style>
</head>
<body>
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="#">Pranav</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'app1:about' %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'app1:contact' %}">Contact</a>
            </li>
            
          </ul>
          <a href="{% url 'app1:login' %}" class="nav-link"><button class="btn btn-secondary">Login</button></a>
          <a href="{% url 'app1:signup' %}" class="nav-link"><button class="btn btn-secondary">SignUp</button></a>
          <a href="{% url 'app1:LogOut' %}" class="nav-link"><button class="btn btn-secondary">LogOut</button></a>
        </div>
      </nav>

      {% block content %}
      {% endblock %}

</body>
</html>

templates/contact.html
{% extends 'base.html' %}

{% block content %}
    <div class="jumbotron">
        <div class="conatiner">
            <h1 class="display-2">Contact Us</h1>
            <br>
            <div class="row">
                <div class="col-sm-3">
                    <h4>Email:- </h4>
                </div>
                <div class="col-sm8-8">
                    Praispranav@gmail.com
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-sm-3">
                    <h4>Phone:-</h4>
                </div>
                <div class="col-sm8-8">
                    +91 7644015588
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-sm-3">
                     <h4>Address:-</h4>
                </div>
                <div class="col-sm8-8">
                    Rampur Parrori East<br>
                    Sitamarhi, Bihar, India
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="jumbotron">
    <div class="container">
        {% for x in b %}

        <h1>{{x.name}}</h1>
        <h5>{{x.cartype}}</h5>
        <!-- <h5>{{x.cartype}}</h5> -->
        <h5>{{x.year}}</h5>
	{% endfor %}
    </div>
</div>
<div class="container">
    <form class="form-group">
        {{form}}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary">
    </form>
</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block content %}

<br>
<br>
<h1>Hello this is the home page {{pran}}</h1>
<div class="jumbotron">
    <div class="container">
        <h3 class="display-3"> Car Dealers </h3>
        <ul>
            {% for x in ca %}
            <li><a href="car/{{x.id}}">{{x.name}}</a></li>
            {% endfor %}
        </ul>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-6 myhover " style="height:30v;margin-top:10vh;">
            <a href="django/contact"> <h1 class="display-4" style="height:100%;">Contact</h1></a>
        </div>
        <div class="col-sm-6 myhover "  style="height:30v;margin-top:10vh;">
            <a href="django/about"> <h1 class="display-4" style="height:40vh;margin:auto auto;">About Us</h1></a>
        </div>
    </div>
</div>

{% endblock %}

templates/index2.html
{% for x in a %}
<li>{{x.name}}</li>
{% endfor %}

templates/login.html
{% extends 'base.html' %}

{% block content %}

<div class="card">
    <div class="card-header">
        <h4 class="display-2">LogIN</h4>
    </div>
    <div class="card-body">
        <form class="form-group" method="POST">
            {% csrf_token %}
            <input placeholder="Username" name="username" class="form-control" type="text" />
            <input placeholder="Password" id="password1" class="form-control" name="password1" type="text" />
            <button type="submit" class="btn btn-primary">LogIn</button>
        </form>
    </div>
</div>

{% endblock %}

templates/signup.html
{% extends 'base.html' %}


{% block content %}

    <form class="form-group">
        {% csrf_token %}
        {{form}}
        <input type="submit" class="btn btn-primary"/>
    </form>

{% endblock %}